import { apiUrl, apiTenantUrl } from '.';

const baseHeader = {
    'Content-Type': 'application/json',
};

const multipartFormHeader = {
    'Content-Type': 'multipart/form-data',
};

const apiConfig = {
    account: {
        login: {
            baseURL: `${apiUrl}v1/account/login`,
            method: 'POST',
            headers: baseHeader,
        },
        loginBasic: {
            baseURL: `${apiUrl}api/token`,
            method: 'POST',
            headers: baseHeader,
        },
        loginSSO: {
            baseURL: `${apiUrl}v1/account/login-sso`,
            method: 'POST',
            headers: baseHeader,
        },
        getProfile: {
            baseURL: `${apiUrl}v1/account/profile`,
            method: 'GET',
            headers: baseHeader,
        },
        updateProfile: {
            baseURL: `${apiUrl}v1/account/update_profile_admin`,
            method: 'PUT',
            headers: baseHeader,
            permissionCode: 'ACC_U_PROFILE_AD',
        },
        getById: {
            baseURL: `${apiUrl}v1/account/get/:id`,
            method: 'GET',
            headers: baseHeader,
            permissionCode: 'ACC_V',
        },
        refreshToken: {
            baseURL: `${apiUrl}v1/account/refresh_token`,
            method: 'POST',
            headers: baseHeader,
        },
        logout: {
            baseURL: `${apiUrl}v1/account/logout`,
            method: 'GET',
            headers: baseHeader,
        },
        changePassword: {
            baseURL: `${apiTenantUrl}v1/account/change-password`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getList: {
            baseURL: `${apiUrl}v1/account/list-admin`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'ACC_L',
        },
        updateAdmin: {
            baseURL: `${apiUrl}v1/account/update_admin`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'ACC_U_AD',
        },
        delete: {
            baseURL: `${apiUrl}v1/account/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'ACC_D',
        },
        createAdmin: {
            baseURL: `${apiUrl}v1/account/create_admin`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'ACC_C_AD',
        },
    },
    user: {
        getList: {
            baseURL: `${apiUrl}v1/account/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'ACC_L',
        },
        autocomplete: {
            baseURL: `${apiUrl}v1/account/auto-complete`,
            method: `GET`,
            headers: baseHeader,
        },
        getById: {
            baseURL: `${apiUrl}v1/account/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'ACC_V',
        },
        create: {
            baseURL: `${apiUrl}v1/account/create_admin`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'ACC_C_AD',
        },
        update: {
            baseURL: `${apiUrl}v1/account/update_admin`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'ACC_U_AD',
        },
        delete: {
            baseURL: `${apiUrl}v1/account/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'ACC_D',
        },
    },
    file: {
        upload: {
            path: `${apiUrl}v1/file/upload`,
            method: 'POST',
            headers: multipartFormHeader,
            isRequiredTenantId: true,
            isUpload: true,
            permissionCode: 'FILE_U',
        },
    },
    post: {
        getList: {
            baseURL: `${apiUrl}api/posts/list`,
            method: `GET`,
            headers: baseHeader,
        },
        getById: {
            baseURL: `${apiUrl}api/posts/get/:id`,
            method: `GET`,
            headers: baseHeader,
        },
        create: {
            baseURL: `${apiUrl}api/posts/create`,
            method: `POST`,
            headers: baseHeader,
        },
        update: {
            baseURL: `${apiUrl}api/posts/update`,
            method: `PUT`,
            headers: baseHeader,
        },
        delete: {
            baseURL: `${apiUrl}api/posts/:id`,
            method: `DELETE`,
            headers: baseHeader,
        },
        autocomplete: {
            baseURL: `${apiUrl}api/posts/auto-complete`,
            method: `GET`,
            headers: baseHeader,
        },
    },
    category: {
        getListForBrand: {
            baseURL: `${apiUrl}v1/category/list?kind=2`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'CATE_L',
        },
        getList: {
            baseURL: `${apiUrl}v1/category/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'CATE_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/category/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'CATE_V',
        },
        create: {
            baseURL: `${apiUrl}v1/category/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'CATE_C',
        },
        update: {
            baseURL: `${apiUrl}v1/category/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'CATE_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/category/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'CATE_D',
        },
        autocomplete: {
            baseURL: `${apiUrl}v1/category/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    device: {
        getListForClient: {
            baseURL: `${apiUrl}v1/device/client-list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEV_L',
        },
        getListForAdmin: {
            baseURL: `${apiUrl}v1/device/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEV_L_AD',
        },
        getByIdForClient: {
            baseURL: `${apiUrl}v1/device/client-get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEV_V',
        },
        getByIdForAdmin: {
            baseURL: `${apiUrl}v1/device/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEV_V_AD',
        },
        create: {
            baseURL: `${apiUrl}v1/device/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'DEV_C',
        },
        update: {
            baseURL: `${apiUrl}v1/device/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'DEV_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/device/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'DEV_D',
        },
        autocomplete: {
            baseURL: `${apiUrl}v1/device/auto-complete`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEV_L',
        },
    },
    groupPermission: {
        getGroupList: {
            baseURL: `${apiUrl}v1/group/list`,
            method: 'GET',
            headers: baseHeader,
            permissionCode: 'GR_L',
        },
        getList: {
            baseURL: `${apiUrl}v1/group/list`,
            method: 'GET',
            headers: baseHeader,
            permissionCode: 'GR_L',
        },
        getPemissionList: {
            baseURL: `${apiUrl}v1/permission/list`,
            method: 'GET',
            headers: baseHeader,
            permissionCode: 'PER_L',
        },
        getPemissionListByApp: {
            baseURL: `${apiUrl}v1/project-role-permission/list-by-app`,
            method: 'GET',
            headers: baseHeader,
            permissionCode: 'PRP_L_A',
        },
        getById: {
            baseURL: `${apiUrl}v1/group/get/:id`,
            method: 'GET',
            headers: baseHeader,
            permissionCode: 'GR_V',
        },
        create: {
            baseURL: `${apiUrl}v1/group/create`,
            method: 'POST',
            headers: baseHeader,
            permissionCode: 'GR_C',
        },
        update: {
            baseURL: `${apiUrl}v1/group/update`,
            method: 'PUT',
            headers: baseHeader,
            permissionCode: 'GR_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/group/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            permissionCode: 'GR_D',
        },
        getGroupListCombobox: {
            baseURL: `${apiUrl}v1/group/list_combobox`,
            method: 'GET',
            headers: baseHeader,
        },
    },
    news: {
        getList: {
            baseURL: `${apiTenantUrl}v1/news/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        getById: {
            baseURL: `${apiTenantUrl}v1/news/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        create: {
            baseURL: `${apiTenantUrl}v1/news/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'NEW_C',
        },
        update: {
            baseURL: `${apiTenantUrl}v1/news/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'NEW_U',
        },
        delete: {
            baseURL: `${apiTenantUrl}v1/news/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'NEW_D',
        },
        autocomplete: {
            baseURL: `${apiTenantUrl}v1/news/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    settings: {
        getList: {
            baseURL: `${apiTenantUrl}v1/setting/list`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'SET_L',
        },
        getById: {
            baseURL: `${apiTenantUrl}v1/setting/get/:id`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'SET_V',
        },
        create: {
            baseURL: `${apiTenantUrl}v1/setting/create`,
            method: 'POST',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'SET_C',
        },
        update: {
            baseURL: `${apiTenantUrl}v1/setting/update`,
            method: 'PUT',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'SET_U',
        },
        delete: {
            baseURL: `${apiTenantUrl}v1/setting/delete/:id`,
            method: 'DELETE',
            headers: baseHeader,
            isRequiredTenantId: true,
            permissionCode: 'SET_D',
        },
        autocomplete: {
            baseURL: `${apiTenantUrl}v1/setting/auto-complete`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
        settings: {
            baseURL: `${apiTenantUrl}v1/setting/settings`,
            method: 'GET',
            headers: baseHeader,
            isRequiredTenantId: true,
        },
    },
    contacts: {
        getList: {
            baseURL: `${apiUrl}v1/contacts/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'CNT_L_AD',
        },
        getListClient: {
            baseURL: `${apiUrl}v1/contacts/client-list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'CNT_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/contacts/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'CNT_V_AD',
        },
        getByIdClient: {
            baseURL: `${apiUrl}v1/contacts/client-get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'CNT_V',
        },
        create: {
            baseURL: `${apiUrl}v1/contacts/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'CNT_C',
        },
        update: {
            baseURL: `${apiUrl}v1/contacts/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'CNT_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/contacts/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'CNT_D',
        },
    },
    employee: {
        getList: {
            baseURL: `${apiUrl}v1/employee/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'EMP_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/employee/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'EMP_V',
        },
        create: {
            baseURL: `${apiUrl}v1/employee/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'EMP_C',
        },
        update: {
            baseURL: `${apiUrl}v1/employee/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'EMP_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/employee/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'EMP_D',
        },
        autocomplete: {
            baseURL: `${apiUrl}v1/employee/auto-complete`,
            method: `GET`,
            headers: baseHeader,
        },
    },
    phoneCall: {
        admin: {
            getList: {
                baseURL: `${apiUrl}v1/phone-call/list`,
                method: `GET`,
                headers: baseHeader,
                permissionCode: 'PC_L',
            },
            getById: {
                baseURL: `${apiUrl}v1/phone-call/get/:id`,
                method: `GET`,
                headers: baseHeader,
                permissionCode: 'PC_V',
            },
            create: {
                baseURL: `${apiUrl}v1/phone-call/create`,
                method: `POST`,
                headers: baseHeader,
                permissionCode: 'PC_C',
            },
            update: {
                baseURL: `${apiUrl}v1/phone-call/update`,
                method: `PUT`,
                headers: baseHeader,
                permissionCode: 'PC_U',
            },
            delete: {
                baseURL: `${apiUrl}v1/phone-call/delete/:id`,
                method: `DELETE`,
                headers: baseHeader,
                permissionCode: 'PC_D',
            },
        },
        employee: {
            getList: {
                baseURL: `${apiUrl}v1/phone-call/employee-list`,
                method: `GET`,
                headers: baseHeader,
                permissionCode: 'PC_EL',
            },
            getById: {
                baseURL: `${apiUrl}v1/phone-call/employee-get/:id`,
                method: `GET`,
                headers: baseHeader,
                permissionCode: 'PC_EV',
            },
            create: {
                baseURL: `${apiUrl}v1/phone-call/employee-create`,
                method: `POST`,
                headers: baseHeader,
                permissionCode: 'PC_EC',
            },
            update: {
                baseURL: `${apiUrl}v1/phone-call/employee-update`,
                method: `PUT`,
                headers: baseHeader,
                permissionCode: 'PC_EU',
            },
            delete: {
                baseURL: `${apiUrl}v1/phone-call/employee-delete/:id`,
                method: `DELETE`,
                headers: baseHeader,
                permissionCode: 'PC_ED',
            },
        },
    },
    deviceEmployee: {
        getList: {
            baseURL: `${apiUrl}v1/device-employee/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEE_L',
        },
        getListForClient: {
            baseURL: `${apiUrl}v1/device-employee/client-list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'CNT_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/device-employee/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEE_V',
        },
        getByIdForClient: {
            baseURL: `${apiUrl}v1/device-employee/client-get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'CNT_V',
        },
        create: {
            baseURL: `${apiUrl}v1/device-employee/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'CNT_C',
        },
        createForClient: {
            baseURL: `${apiUrl}v1/device-employee/client-create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'DEE_C',
        },
        update: {
            baseURL: `${apiUrl}v1/device-employee/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'DEE_U',
        },
        updateForClient: {
            baseURL: `${apiUrl}v1/device-employee/client-update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'CNT_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/device-employee/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'DEE_D',
        },
    },
    message: {
        getList: {
            baseURL: `${apiUrl}v1/message/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'MES_L_AD',
        },
        getListForClient: {
            baseURL: `${apiUrl}v1/message/client-list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'MES_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/message/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'MES_V_AD',
        },
        getByIdForClient: {
            baseURL: `${apiUrl}v1/message/client-get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'MES_V',
        },
        create: {
            baseURL: `${apiUrl}v1/message/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'MES_C',
        },
        update: {
            baseURL: `${apiUrl}v1/message/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'MES_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/message/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'MES_D',
        },
    },
    nation: {
        getList: {
            baseURL: `${apiUrl}v1/nation/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'NAT_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/nation/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'NAT_V',
        },
        autoComplete: {
            baseURL: `${apiUrl}v1/nation/auto-complete`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'NAT_L',
        },
        create: {
            baseURL: `${apiUrl}v1/nation/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'NAT_C',
        },
        update: {
            baseURL: `${apiUrl}v1/nation/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'NAT_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/nation/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'NAT_D',
        },
        getClientList: {
            baseURL: `${apiUrl}v1/nation/client-list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'NAT_L',
        },
        getClientById: {
            baseURL: `${apiUrl}v1/nation/client-get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'NAT_V',
        },
    },
    tag: {
        getList: {
            baseURL: `${apiUrl}v1/tag/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'TAG_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/tag/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'TAG_V',
        },
        create: {
            baseURL: `${apiUrl}v1/tag/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'TAG_C',
        },
        update: {
            baseURL: `${apiUrl}v1/tag/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'TAG_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/tag/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'TAG_D',
        },
    },
    deviceEmployeeLog: {
        getList: {
            baseURL: `${apiUrl}v1/device-employee-log/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEL_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/device-employee-log/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEL_V',
        },
    },
    department: {
        getList: {
            baseURL: `${apiUrl}v1/department/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEP_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/department/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEP_V',
        },
        create: {
            baseURL: `${apiUrl}v1/department/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'DEP_C',
        },
        update: {
            baseURL: `${apiUrl}v1/department/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'DEP_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/department/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'DEP_D',
        },
        autocomplete: {
            baseURL: `${apiUrl}v1/department/auto-complete`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DEP_L',
        },
    },
    deviceHistoryCost: {
        getList: {
            baseURL: `${apiUrl}v1/device-cost-history/list`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DCH_L',
        },
        getById: {
            baseURL: `${apiUrl}v1/device-cost-history/get/:id`,
            method: `GET`,
            headers: baseHeader,
            permissionCode: 'DCH_V',
        },
        create: {
            baseURL: `${apiUrl}v1/device-cost-history/create`,
            method: `POST`,
            headers: baseHeader,
            permissionCode: 'DCH_C',
        },
        update: {
            baseURL: `${apiUrl}v1/device-cost-history/update`,
            method: `PUT`,
            headers: baseHeader,
            permissionCode: 'DCH_U',
        },
        delete: {
            baseURL: `${apiUrl}v1/device-cost-history/delete/:id`,
            method: `DELETE`,
            headers: baseHeader,
            permissionCode: 'DCH_D',
        },
    },
};

export default apiConfig;
